import { useMemo } from 'react'
import { useConnection, useWallet } from '@solana/wallet-adapter-react'
import { Program, AnchorProvider, web3, BN } from '@coral-xyz/anchor'
import { LeveragedMeme } from '../types/leveraged_meme'
import { PROGRAM_ID } from '../types/program'

// IDL (will be generated by anchor build)
const IDL = {
  version: '0.1.0',
  name: 'leveraged_meme',
  instructions: [
    {
      name: 'initializeToken',
      accounts: [
        { name: 'creator', isMut: true, isSigner: true },
        { name: 'tokenMint', isMut: true, isSigner: true },
        { name: 'tokenState', isMut: true, isSigner: false },
        { name: 'curveState', isMut: true, isSigner: false },
        { name: 'feeVault', isMut: true, isSigner: false },
        { name: 'curveTokenAccount', isMut: true, isSigner: false },
        { name: 'lpTokenAccount', isMut: true, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
        { name: 'tokenProgram', isMut: false, isSigner: false },
        { name: 'rent', isMut: false, isSigner: false },
        { name: 'clock', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'name', type: 'string' },
        { name: 'symbol', type: 'string' },
        { name: 'uri', type: 'string' },
        { name: 'leverage', type: 'u8' },
        { name: 'direction', type: { defined: 'Direction' } },
        { name: 'perpMarketIndex', type: 'u16' },
      ],
    },
    {
      name: 'buy',
      accounts: [
        { name: 'buyer', isMut: true, isSigner: true },
        { name: 'tokenState', isMut: true, isSigner: false },
        { name: 'curveState', isMut: true, isSigner: false },
        { name: 'tokenMint', isMut: true, isSigner: false },
        { name: 'buyerTokenAccount', isMut: true, isSigner: false },
        { name: 'curveTokenAccount', isMut: true, isSigner: false },
        { name: 'feeVault', isMut: true, isSigner: false },
        { name: 'protocolFeeAccount', isMut: true, isSigner: false },
        { name: 'creatorFeeAccount', isMut: true, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
        { name: 'tokenProgram', isMut: false, isSigner: false },
        { name: 'clock', isMut: false, isSigner: false },
      ],
      args: [{ name: 'amount', type: 'u64' }],
    },
    {
      name: 'buyWithDrift',
      accounts: [
        { name: 'buyer', isMut: true, isSigner: true },
        { name: 'tokenState', isMut: true, isSigner: false },
        { name: 'curveState', isMut: true, isSigner: false },
        { name: 'tokenMint', isMut: true, isSigner: false },
        { name: 'buyerTokenAccount', isMut: true, isSigner: false },
        { name: 'curveTokenAccount', isMut: true, isSigner: false },
        { name: 'feeVault', isMut: true, isSigner: false },
        { name: 'protocolFeeAccount', isMut: true, isSigner: false },
        { name: 'creatorFeeAccount', isMut: true, isSigner: false },
        { name: 'driftProgram', isMut: false, isSigner: false },
        { name: 'driftState', isMut: true, isSigner: false },
        { name: 'driftUser', isMut: true, isSigner: false },
        { name: 'driftUserStats', isMut: true, isSigner: false },
        { name: 'pythPriceFeed', isMut: false, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
        { name: 'tokenProgram', isMut: false, isSigner: false },
        { name: 'clock', isMut: false, isSigner: false },
      ],
      args: [{ name: 'amount', type: 'u64' }],
    },
    {
      name: 'sell',
      accounts: [
        { name: 'seller', isMut: true, isSigner: true },
        { name: 'tokenState', isMut: true, isSigner: false },
        { name: 'curveState', isMut: true, isSigner: false },
        { name: 'tokenMint', isMut: true, isSigner: false },
        { name: 'sellerTokenAccount', isMut: true, isSigner: false },
        { name: 'curveTokenAccount', isMut: true, isSigner: false },
        { name: 'feeVault', isMut: true, isSigner: false },
        { name: 'protocolFeeAccount', isMut: true, isSigner: false },
        { name: 'creatorFeeAccount', isMut: true, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
        { name: 'tokenProgram', isMut: false, isSigner: false },
        { name: 'clock', isMut: false, isSigner: false },
      ],
      args: [{ name: 'amount', type: 'u64' }],
    },
    {
      name: 'graduate',
      accounts: [
        { name: 'caller', isMut: true, isSigner: true },
        { name: 'tokenState', isMut: true, isSigner: false },
        { name: 'curveState', isMut: true, isSigner: false },
        { name: 'tokenMint', isMut: true, isSigner: false },
        { name: 'curveTokenAccount', isMut: true, isSigner: false },
        { name: 'lpTokenAccount', isMut: true, isSigner: false },
        { name: 'feeVault', isMut: true, isSigner: false },
        { name: 'protocolFeeAccount', isMut: true, isSigner: false },
        { name: 'creator', isMut: true, isSigner: false },
        { name: 'ammPool', isMut: true, isSigner: false },
        { name: 'tokenProgram', isMut: false, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
        { name: 'clock', isMut: false, isSigner: false },
      ],
      args: [],
    },
    {
      name: 'setPause',
      accounts: [
        { name: 'authority', isMut: true, isSigner: true },
        { name: 'tokenState', isMut: true, isSigner: false },
        { name: 'tokenMint', isMut: false, isSigner: false },
        { name: 'clock', isMut: false, isSigner: false },
      ],
      args: [{ name: 'paused', type: 'bool' }],
    },
    {
      name: 'syncPerpPosition',
      accounts: [
        { name: 'caller', isMut: true, isSigner: true },
        { name: 'tokenState', isMut: true, isSigner: false },
        { name: 'tokenMint', isMut: false, isSigner: false },
        { name: 'pythPriceFeed', isMut: false, isSigner: false },
        { name: 'clock', isMut: false, isSigner: false },
      ],
      args: [],
    },
  ],
  accounts: [
    {
      name: 'TokenState',
      type: {
        kind: 'struct',
        fields: [
          { name: 'creator', type: 'publicKey' },
          { name: 'tokenMint', type: 'publicKey' },
          { name: 'name', type: 'string' },
          { name: 'symbol', type: 'string' },
          { name: 'uri', type: 'string' },
          { name: 'leverage', type: 'u8' },
          { name: 'direction', type: { defined: 'Direction' } },
          { name: 'perpMarketIndex', type: 'u16' },
          { name: 'curveState', type: { defined: 'CurveState' } },
          { name: 'perpPosition', type: { defined: 'PerpPosition' } },
          { name: 'feeVault', type: 'publicKey' },
          { name: 'graduated', type: 'bool' },
          { name: 'ammPool', type: { option: 'publicKey' } },
          { name: 'createdAt', type: 'i64' },
          { name: 'updatedAt', type: 'i64' },
          { name: 'paused', type: 'bool' },
          { name: 'totalFeesCollected', type: 'u64' },
        ],
      },
    },
    {
      name: 'CurveState',
      type: {
        kind: 'struct',
        fields: [
          { name: 'virtualSolReserve', type: 'u64' },
          { name: 'virtualTokenReserve', type: 'u64' },
          { name: 'realSolReserve', type: 'u64' },
          { name: 'realTokenReserve', type: 'u64' },
          { name: 'k', type: 'u128' },
        ],
      },
    },
    {
      name: 'PerpPosition',
      type: {
        kind: 'struct',
        fields: [
          { name: 'baseAssetAmount', type: 'i64' },
          { name: 'entryPrice', type: 'u64' },
          { name: 'lastMarkPrice', type: 'u64' },
          { name: 'unrealizedPnl', type: 'i64' },
          { name: 'margin', type: 'u64' },
          { name: 'leverage', type: 'u8' },
          { name: 'direction', type: { defined: 'Direction' } },
          { name: 'lastUpdate', type: 'i64' },
        ],
      },
    },
    {
      name: 'FeeVault',
      type: {
        kind: 'struct',
        fields: [
          { name: 'tokenMint', type: 'publicKey' },
          { name: 'totalCollected', type: 'u64' },
          { name: 'creatorClaimed', type: 'u64' },
          { name: 'protocolClaimed', type: 'u64' },
          { name: 'creatorShareBps', type: 'u64' },
        ],
      },
    },
  ],
  types: [
    {
      name: 'Direction',
      type: {
        kind: 'enum',
        variants: [{ name: 'Long' }, { name: 'Short' }],
      },
    },
  ],
  events: [
    {
      name: 'TokenCreated',
      fields: [
        { name: 'creator', type: 'publicKey', index: false },
        { name: 'tokenMint', type: 'publicKey', index: false },
        { name: 'name', type: 'string', index: false },
        { name: 'symbol', type: 'string', index: false },
        { name: 'leverage', type: 'u8', index: false },
        { name: 'direction', type: { defined: 'Direction' }, index: false },
        { name: 'timestamp', type: 'i64', index: false },
      ],
    },
    {
      name: 'TokenBought',
      fields: [
        { name: 'buyer', type: 'publicKey', index: false },
        { name: 'tokenMint', type: 'publicKey', index: false },
        { name: 'solAmount', type: 'u64', index: false },
        { name: 'tokenAmount', type: 'u64', index: false },
        { name: 'perpPositionSize', type: 'u64', index: false },
        { name: 'timestamp', type: 'i64', index: false },
      ],
    },
    {
      name: 'TokenSold',
      fields: [
        { name: 'seller', type: 'publicKey', index: false },
        { name: 'tokenMint', type: 'publicKey', index: false },
        { name: 'tokenAmount', type: 'u64', index: false },
        { name: 'solAmount', type: 'u64', index: false },
        { name: 'timestamp', type: 'i64', index: false },
      ],
    },
    {
      name: 'TokenGraduated',
      fields: [
        { name: 'tokenMint', type: 'publicKey', index: false },
        { name: 'ammPool', type: 'publicKey', index: false },
        { name: 'finalMarketCap', type: 'u64', index: false },
        { name: 'timestamp', type: 'i64', index: false },
      ],
    },
  ],
  errors: [
    { code: 6000, name: 'NameTooLong', msg: 'Name too long (max 32 characters)' },
    { code: 6001, name: 'SymbolTooLong', msg: 'Symbol too long (max 10 characters)' },
    { code: 6002, name: 'LeverageTooHigh', msg: 'Leverage too high (max 5x)' },
    { code: 6003, name: 'LeverageTooLow', msg: 'Leverage too low (min 2x)' },
    { code: 6004, name: 'InvalidPerpMarket', msg: 'Invalid perp market index' },
    { code: 6005, name: 'AlreadyGraduated', msg: 'Token already graduated' },
    { code: 6006, name: 'NotGraduated', msg: 'Token not yet graduated' },
    { code: 6007, name: 'InsufficientLiquidity', msg: 'Insufficient liquidity in curve' },
    { code: 6008, name: 'SlippageExceeded', msg: 'Slippage tolerance exceeded' },
    { code: 6009, name: 'LiquidationRisk', msg: 'Perp position would be liquidated' },
    { code: 6010, name: 'GraduationThresholdNotMet', msg: 'Graduation threshold not reached' },
    { code: 6011, name: 'ContractPaused', msg: 'Contract is paused' },
    { code: 6012, name: 'Unauthorized', msg: 'Unauthorized' },
    { code: 6013, name: 'MathOverflow', msg: 'Math overflow' },
    { code: 6014, name: 'InvalidFeeConfig', msg: 'Invalid fee configuration' },
    { code: 6015, name: 'DriftError', msg: 'Drift integration error' },
    { code: 6016, name: 'OracleError', msg: 'Price oracle error' },
    { code: 6017, name: 'InvariantViolation', msg: 'Bonding curve invariant violated' },
  ],
}

export function useProgram() {
  const { connection } = useConnection()
  const wallet = useWallet()

  const program = useMemo(() => {
    if (!wallet.publicKey) return null
    
    const provider = new AnchorProvider(
      connection,
      wallet as any,
      AnchorProvider.defaultOptions()
    )
    
    return new Program(IDL as any, PROGRAM_ID, provider)
  }, [connection, wallet])

  return program
}
