[features]
seeds = true
skip-lint = false

[programs.localnet]
leveraged_meme = "9siEsegivtASLpuRHzMC9UEBcCuzeKe8iREadFEZqCAP"

[programs.devnet]
leveraged_meme = "9siEsegivtASLpuRHzMC9UEBcCuzeKe8iREadFEZqCAP"

[programs.mainnet]
leveraged_meme = "9siEsegivtASLpuRHzMC9UEBcCuzeKe8iREadFEZqCAP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

type = "es"

[test]
startup_wait = 10000

[test.validator]
bind_address = "127.0.0.1"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "dRiftyHA39MWEi3m9aunc5MzRF1JYuBsbn6VPcn33UH"

[[test.validator.clone]]
address = "J83w4HKfqxwcq3BEMMkPFSppX3gqekLyLJBexebFVkix"
